---
- include: install.yml
  tags: bitcoind

- include: cpulimit.yml
  when: bitcoind_cpulimit
  tags: bitcoind

- name: add bitcoind user
  user: >
    name=bitcoind
    system=yes
    createhome=no
  tags: bitcoind

- name: configure bitcoind
  template: >
    src=bitcoin.conf
    dest=/etc/bitcoin.conf
    mode=640
    owner=root
    group=bitcoind
  notify:
    - restart bitcoind
  tags: bitcoind

- name: create bitcoind data directory
  file: >
    dest=/var/lib/bitcoind
    mode=755
    owner=bitcoind
    group=bitcoind
    state=directory
  tags: bitcoind

- name: install bitcoind systemd script
  template: >
    src=bitcoind.service
    dest=/etc/systemd/system/bitcoind.service
    mode=644
    owner=root
    group=root
  notify:
    - reload systemd
    - restart bitcoind
  tags: bitcoind

- name: enable bitcoind
  service: >
    name=bitcoind
    enabled=yes
    state=started
  tags: bitcoind

- name: install bitcoind monit script
  template: >
    src=bitcoind.monit
    dest=/etc/monit/conf.d/bitcoind
    mode=644
    owner=root
    group=root
  notify:
    - reload monit
  tags: [bitcoind, monit]

- name: whitelist bitcoind in firewall
  ufw: rule=allow port={{ bitcoind_port }} proto=tcp
  when: ufw
  tags: [bitcoind, ufw]
