---
- name: add bitcoind apt repository
  apt_repository: repo='ppa:bitcoin/bitcoin'
  tags: bitcoind

- name: install bitcoind
  apt: name=bitcoind state=latest
  with_items:
    - bitcoind
  notify:
    - restart bitcoind
  tags: bitcoind

- name: add bitcoind user
  user: >
    name=bitcoind
    system=yes
    createhome=no
  tags: bitcoind

# Ubuntu has a cpulimit package, but it's a different version that can't do
# process groups.
- name: install cpulimit dependencies
  apt: name=build-essential
  when: bitcoind_cpulimit
  tags: bitcoind

- name: download cpulimit
  git: >
    repo=https://github.com/opsengine/cpulimit.git
    dest=/opt/cpulimit
    version=fd48ecf5a123ddaf5dd02d7928f975db719975bb
  register: cpulimit_clone_result
  when: bitcoind_cpulimit
  tags: bitcoind

- name: build cpulimit
  command: make chdir=/opt/cpulimit
  when: bitcoind_cpulimit and cpulimit_clone_result|changed
  tags: bitcoind

- name: configure bitcoind
  template: >
    src=bitcoin.conf
    dest=/etc/bitcoin.conf
    mode=640
    owner=root
    group=bitcoind
  notify:
    - restart bitcoind
  tags: bitcoind

- name: create bitcoind data directory
  file: >
    dest=/var/lib/bitcoind
    mode=755
    owner=bitcoind
    group=bitcoind
    state=directory
  tags: bitcoind

- name: install bitcoind upstart script
  template: >
    src=upstart.conf
    dest=/etc/init/bitcoind.conf
    mode=644
    owner=root
    group=root
  notify:
    - restart bitcoind
  tags: bitcoind

# old versions of honeybadger might leave this behind (March 6th, 2015)
- name: remove old bitcoind upstart override file
  file: >
    dest=/etc/init/bitcoind.override
    state=absent
  notify:
    - restart bitcoind
  tags: bitcoind

- name: enable bitcoind
  service: >
    name=bitcoind
    enabled=yes
    state=started
  tags: bitcoind

- name: install bitcoind monit script
  template: >
    src=bitcoind.monit
    dest=/etc/monit/conf.d/bitcoind
    mode=644
    owner=root
    group=root
  notify:
    - reload monit
  tags: [bitcoind, monit]

- name: whitelist bitcoind in firewall
  ufw: rule=allow port={{ bitcoind_port }} proto=tcp
  when: ufw
  tags: [bitcoind, ufw]
