---
- hosts: all
  remote_user: root
  become: no
  roles:
    # common setup (needed by both tor and bitcoind)
    - bootstrap
    - openssh
    - ufw
    - systemd
    - monit
    - www
    # core services
    - {role: bitcoind, when: bitcoind}
    - {role: tor, when: tor}
    # these are extras, feel free to remove them:
    - htop
    - {role: bitcoind-rpc, when: bitcoind}
    - {role: tor-arm, when: tor}
    - aptitude
    - unattended-upgrades
